### ISSUE TITLE
Minimizing or closing the app to minimize does not show icon in the notification panel

### ISSUE THREAD

**Issue by grande-mephistopheles** [flathub/org.qbittorrent.qBittorrent#43] opened 2020-09-05 17:27 UTC
**Note:** This issue is only specific to the flatpak version. The distro repository version or the version from ppa is not affected.

When the app is closed or minimized , by default it is minimized to notification panel and keeps running which is the expected behaviour. However, the icon for qbittorrent is not shown in the panel, which confuses the user whether it is running or not.

In the distro repository or ppa version the minimized app is shown the notification panel, clearing any confusion.

**Additional Note:** 
OS: Linux Mint 20 Cinnamon
qBittorent version: 4.2.5

**Comment by Erick555** [comment] 2020-09-05 17:38
Do you mean the tray icon isn't shown? It works for me however it may conflict if you run other flatpak apps with tray icon at the same time. This is known generic flatpak issue and there is no fix for that.

**Comment by Erick555** [comment] 2020-09-05 18:08
You may try running `flatpak run --own-name=org.kde.StatusNotifierItem-2-2 org.qbittorrent.qBittorrent`

**Comment by Erick555** [comment] 2020-09-05 18:09
Duplicate of https://github.com/flathub/org.qbittorrent.qBittorrent/issues/14 ?

**Comment by grande-mephistopheles** [comment] 2020-09-06 03:06
> Duplicate of #14 ?

I was under the impression that it's a problem with the GNOME shell. If not it seems it's present in every desktop. Also the bug is from two years ago. If not fixed already then I have to say flatpak is not officially supported anymore.

**Comment by Erick555** [comment] 2020-09-06 08:26
Flatpak was never officially supported. I can only say that it works for me on KDE without need for any fixes.

**Comment by grande-mephistopheles** [comment] 2020-09-06 13:52
Untill this issue is fixed, the only workaround is unchecking the following options from the "Behavior" tab
![qbt](https://user-images.githubusercontent.com/58479925/92327277-09be4f00-f048-11ea-90af-a34b601708bd.jpg)

**Comment by Erick555** [comment] 2020-09-06 15:35
Hm, so the tray icons works but minimizing to tray is broken? It may be different issue then

**Comment by grande-mephistopheles** [comment] 2020-09-06 15:47
> Hm, so the tray icons works but minimizing to tray is broken? It may be different issue then

No, you misunderstood it. The icon never shows up. Either open/close/minimized

**Comment by eszlari** [comment] 2020-10-04 21:23
duplicate of #14

**Closed by eszlari** 2020-10-04 21:23 UTC
